x-php: &php
  build:
    context: docker/php
    args:
      PHP_VERSION: 8.4
      COMPOSER_VERSION: 2.8
      HOST_UID: ${HOST_UID:-1001}
      HOST_GID: ${HOST_GID:-1001}
  image: php:8.4-ieducar
  working_dir: /var/www/ieducar
  volumes:
    - ./:/var/www/ieducar
  environment:
    CACHE_DRIVER: redis
    REDIS_HOST: demo_redis
    DB_HOST: demo_postgres
    PGPASSWORD: ${DB_PASSWORD}
  extra_hosts:
    - host.docker.internal:host-gateway

services:

  php:
    <<: *php
    command: tail -f /dev/null

  fpm:
    <<: *php

  nginx:
    image: nginx:1.28-alpine
    working_dir: /var/www/ieducar
    volumes:
      - ./:/var/www/ieducar
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/snippets:/etc/nginx/snippets/
    depends_on:
      - fpm
