x-php: &php
  build:
    context: docker/php
    args:
      PHP_VERSION: 8.4
      COMPOSER_VERSION: 2.8
      HOST_UID: ${HOST_UID:-1001}
      HOST_GID: ${HOST_GID:-1001}
  image: php:8.4-ieducar
  working_dir: /var/www/ieducar
  volumes:
    - ./:/var/www/ieducar
  depends_on:
    postgres:
      condition: service_started
    redis:
      condition: service_started
  environment:
    CACHE_DRIVER: redis
    REDIS_HOST: redis
    DB_HOST: postgres
    PGPASSWORD: ${DB_PASSWORD}
  extra_hosts:
    - host.docker.internal:host-gateway

services:

  php:
    <<: *php
    command: tail -f /dev/null
    depends_on: []

  fpm:
    <<: *php

  horizon:
    <<: *php
    command: /var/www/ieducar/artisan horizon
    restart: always

  nginx:
    image: nginx:1.28-alpine
    working_dir: /var/www/ieducar
    volumes:
      - ./:/var/www/ieducar
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/snippets:/etc/nginx/snippets/
    depends_on:
      - fpm

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_USERNAME}
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    restart: always

volumes:
  postgres:
